before:
  hooks:
    - go mod tidy
    - go generate ./...

build:
  binary: appy
  main: ./cmd/appy/appy.go
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - 386
  - amd64
  ignore:
  - goos: darwin
    goarch: 386
  env:
  - CGO_ENABLED=0

archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc

checksum:
  name_template: checksums.txt

env:
  - GO111MODULE=on

snapshot:
  name_template: "{{ .Tag }}"
