# MacOS system
.DS_Store

# Editor directories and files
.idea
.vscode
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# Log files
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# 3rd party dependencies
node_modules
vendor

# Misc.
*.upx
.docker
.editorconfig
.git
.gitignore
.tool-versions
.terraform
Brewfile.lock.json
README.md
terraform.tfstate
terraform.tfvars
{{.Project.Name}}
dist
tmp
