package cmd

import (
	"io/ioutil"
	"net/http"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"

	"github.com/dustin/go-humanize"
	"github.com/otiai10/copy"
	"github.com/shurcooL/vfsgen"

	appyhttp "github.com/appist/appy/internal/http"
	appysupport "github.com/appist/appy/internal/support"
)

var (
	mainAssets = "pkg/bootstrap/assets.go"
)

// NewBuildCommand compiles the static assets into go files and build the release mode binary (debug build only)
func NewBuildCommand(logger *appysupport.Logger, s *appyhttp.Server) *Command {
	return &Command{
		Use:   "build",
		Short: "Compile the static assets into go files and build the release mode binary (debug build only)",
		Run: func(cmd *Command, args []string) {
			wd, err := os.Getwd()
			if err != nil {
				logger.Fatal(err)
			}

			binaryName := path.Base(wd)
			assetsPath := "assets"
			assetsPathForSSR := assetsPath + "/" + appysupport.SSRPaths["root"]
			os.RemoveAll(assetsPath)

			if _, err := os.Stat("./package.json"); !os.IsNotExist(err) {
				ssrPaths := []string{}
				for _, route := range s.Routes() {
					if route.Method == "GET" {
						ssrPaths = append(ssrPaths, route.Path)
					}
				}

				logger.Info("Building the web app...")
				buildWebCmd := exec.Command("npm", "run", "build")
				buildWebCmd.Env = os.Environ()
				buildWebCmd.Env = append(buildWebCmd.Env, "APPY_SSR_PATHS="+strings.Join(ssrPaths, ","))
				buildWebCmd.Dir = wd
				buildWebCmd.Stdout = os.Stdout
				buildWebCmd.Stderr = os.Stderr
				if err := buildWebCmd.Run(); err != nil {
					logger.Fatal(err)
				}
				logger.Info("Building the web app... DONE")
			}

			logger.Info("Copying server-side assets...")
			err = copy.Copy(appysupport.SSRPaths["docker"], assetsPathForSSR+"/"+appysupport.SSRPaths["docker"])
			if err != nil {
				logger.Fatal(err)
			}

			err = copy.Copy(appysupport.SSRPaths["view"], assetsPathForSSR+"/"+appysupport.SSRPaths["view"])
			if err != nil {
				logger.Fatal(err)
			}

			err = copy.Copy(appysupport.SSRPaths["locale"], assetsPathForSSR+"/"+appysupport.SSRPaths["locale"])
			if err != nil {
				logger.Fatal(err)
			}

			err = copy.Copy(appysupport.SSRPaths["config"], assetsPathForSSR+"/"+appysupport.SSRPaths["config"])
			if err != nil {
				logger.Fatal(err)
			}

			keyFiles, _ := filepath.Glob(assetsPathForSSR + "/" + appysupport.SSRPaths["config"] + "/*.key")
			for _, keyFile := range keyFiles {
				os.Remove(keyFile)
			}

			logger.Info("Copying server-side assets... DONE")
			oldStdout := os.Stdout
			os.Stdout = nil

			generateMainAssets(logger)
			logger.Infof("Compiling assets folder into '%s'...", mainAssets)
			err = vfsgen.Generate(http.Dir(assetsPath), vfsgen.Options{PackageName: "bootstrap", Filename: mainAssets, VariableName: "assets"})
			if err != nil {
				logger.Fatal(err)
			}
			logger.Infof("Compiling assets folder into '%s'... DONE", mainAssets)
			os.Stdout = oldStdout

			if _, err := os.Stat(wd + "/pkg/graphql/config.yml"); !os.IsNotExist(err) {
				logger.Info("Generating GraphQL boilerplate code...")
				err = generateGQL(s)
				if err != nil {
					logger.Fatal(err.Error())
				}

				logger.Info("Generating GraphQL boilerplate code... DONE")
			}

			logger.Info("Building the binary...")
			goPath, err := exec.LookPath("go")
			if err != nil {
				logger.Fatal(err)
			}

			buildBinaryCmd := exec.Command(goPath, "build", "-a", "-tags", "netgo", "-ldflags", "-w -extldflags '-static' -X github.com/appist/appy/internal/support.Build=release", "-o", binaryName, ".")
			buildBinaryCmd.Stderr = os.Stderr
			if err = buildBinaryCmd.Run(); err != nil {
				logger.Fatal(err)
			}
			fi, _ := os.Stat(binaryName)
			logger.Infof("Building the binary... DONE (size: %s)", humanize.Bytes(uint64(fi.Size())))

			_, err = exec.LookPath("upx")
			if err == nil {
				logger.Info("Compressing the binary with upx...")
				compressBinaryCmd := exec.Command("upx", binaryName)
				compressBinaryCmd.Stderr = os.Stderr
				if err = compressBinaryCmd.Run(); err != nil {
					logger.Fatal(err)
				}
				fi, _ := os.Stat(binaryName)
				logger.Infof("Compressing the binary with upx... DONE (size: %s)", humanize.Bytes(uint64(fi.Size())))
			}
		},
	}
}

func generateMainAssets(logger *appysupport.Logger) {
	os.Remove(mainAssets)

	template := []byte(`
// Generated by appy. DO NOT EDIT.
package main
import "net/http"
var assets http.FileSystem
`)
	err := ioutil.WriteFile(mainAssets, template, 0644)
	if err != nil {
		logger.Fatal(err)
	}
}
