package cmd

import (
	"io/ioutil"
	"net/http"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"

	"github.com/dustin/go-humanize"
	"github.com/otiai10/copy"
	"github.com/shurcooL/vfsgen"

	ah "github.com/appist/appy/http"
	"github.com/appist/appy/support"
)

var (
	mainAssets = "pkg/app/assets.go"
)

// NewBuildCommand compile the static assets into go files and build the release mode binary (only available in debug build).
func NewBuildCommand(assets *support.Assets, logger *support.Logger, server *ah.Server) *Command {
	return &Command{
		Use:   "build",
		Short: "Compile the static assets into go files and build the release mode binary (only available in debug build)",
		Run: func(cmd *Command, args []string) {
			wd, err := os.Getwd()
			if err != nil {
				logger.Fatal(err)
			}

			binaryName := path.Base(wd)
			releasePath := "dist"
			releasePathSSR := releasePath + "/" + assets.SSRRelease()
			os.RemoveAll(releasePath)

			if _, err := os.Stat("./package.json"); !os.IsNotExist(err) {
				ssrPaths := []string{}
				for _, route := range server.Routes() {
					if route.Method == "GET" {
						ssrPaths = append(ssrPaths, route.Path)
					}
				}

				logger.Info("Building the web app...")
				buildWebCmd := exec.Command("npm", "run", "build")
				buildWebCmd.Env = os.Environ()
				buildWebCmd.Env = append(buildWebCmd.Env, "APPY_SSR_PATHS="+strings.Join(ssrPaths, ","))
				buildWebCmd.Dir = wd
				buildWebCmd.Stdout = os.Stdout
				buildWebCmd.Stderr = os.Stderr
				if err := buildWebCmd.Run(); err != nil {
					logger.Fatal(err)
				}
				logger.Info("Building the web app... DONE")
			}

			logger.Infof("Copying server-side assets into '%s' folder...", releasePath)
			err = copy.Copy(assets.Layout()["docker"], releasePathSSR+"/"+assets.Layout()["docker"])
			if err != nil {
				logger.Fatal(err)
			}

			err = copy.Copy(assets.Layout()["view"], releasePathSSR+"/"+assets.Layout()["view"])
			if err != nil {
				logger.Fatal(err)
			}

			err = copy.Copy(assets.Layout()["locale"], releasePathSSR+"/"+assets.Layout()["locale"])
			if err != nil {
				logger.Fatal(err)
			}

			err = copy.Copy(assets.Layout()["config"], releasePath+"/"+assets.Layout()["config"])
			if err != nil {
				logger.Fatal(err)
			}

			keyFiles, _ := filepath.Glob(releasePathSSR + "/" + assets.Layout()["config"] + "/*.key")
			for _, keyFile := range keyFiles {
				os.Remove(keyFile)
			}

			logger.Infof("Copying server-side assets into '%s' folder... DONE", releasePath)
			oldStdout := os.Stdout
			os.Stdout = nil

			generateMainAssets(logger)
			logger.Infof("Compiling '%s' folder into '%s'...", releasePath, mainAssets)
			err = vfsgen.Generate(http.Dir(releasePath), vfsgen.Options{PackageName: "app", Filename: mainAssets, VariableName: "assets"})
			if err != nil {
				logger.Fatal(err)
			}
			logger.Infof("Compiling '%s' folder into '%s'... DONE", releasePath, mainAssets)
			os.Stdout = oldStdout

			if _, err := os.Stat(wd + "/pkg/graphql/config.yml"); !os.IsNotExist(err) {
				logger.Info("Generating GraphQL boilerplate code...")
				err = generateGQL()
				if err != nil {
					logger.Fatal(err.Error())
				}

				logger.Info("Generating GraphQL boilerplate code... DONE")
			}

			logger.Info("Building the binary...")
			goPath, err := exec.LookPath("go")
			if err != nil {
				logger.Fatal(err)
			}

			buildBinaryCmd := exec.Command(goPath, "build", "-a", "-tags", "netgo jsoniter", "-ldflags", "-w -extldflags '-static' -X github.com/appist/appy/support.Build=release", "-o", binaryName, ".")
			buildBinaryCmd.Stderr = os.Stderr
			if err = buildBinaryCmd.Run(); err != nil {
				logger.Fatal(err)
			}
			fi, _ := os.Stat(binaryName)
			logger.Infof("Building the binary... DONE (size: %s)", humanize.Bytes(uint64(fi.Size())))

			_, err = exec.LookPath("upx")
			if err == nil {
				logger.Info("Compressing the binary with upx...")
				compressBinaryCmd := exec.Command("upx", binaryName)
				compressBinaryCmd.Stderr = os.Stderr
				if err = compressBinaryCmd.Run(); err != nil {
					logger.Fatal(err)
				}
				fi, _ := os.Stat(binaryName)
				logger.Infof("Compressing the binary with upx... DONE (size: %s)", humanize.Bytes(uint64(fi.Size())))
			}
		},
	}
}

func generateMainAssets(logger *support.Logger) {
	os.Remove(mainAssets)

	template := []byte(`
// Generated by appy. DO NOT EDIT.

package app

import "net/http"

var assets http.FileSystem
`)
	err := ioutil.WriteFile(mainAssets, template, 0644)
	if err != nil {
		logger.Fatal(err)
	}
}
