// Code generated by mockery v1.1.2. DO NOT EDIT.

package record

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// MockedModel is an autogenerated mock type for the Modeler type
type MockedModel struct {
	mock.Mock
}

// All provides a mock function with given fields:
func (_m *MockedModel) All() Modeler {
	ret := _m.Called()

	var r0 Modeler
	if rf, ok := ret.Get(0).(func() Modeler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Begin provides a mock function with given fields:
func (_m *MockedModel) Begin() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BeginContext provides a mock function with given fields: ctx, opts
func (_m *MockedModel) BeginContext(ctx context.Context, opts *sql.TxOptions) error {
	ret := _m.Called(ctx, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) error); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Commit provides a mock function with given fields:
func (_m *MockedModel) Commit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Count provides a mock function with given fields:
func (_m *MockedModel) Count() Modeler {
	ret := _m.Called()

	var r0 Modeler
	if rf, ok := ret.Get(0).(func() Modeler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Create provides a mock function with given fields:
func (_m *MockedModel) Create() Modeler {
	ret := _m.Called()

	var r0 Modeler
	if rf, ok := ret.Get(0).(func() Modeler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Delete provides a mock function with given fields:
func (_m *MockedModel) Delete() Modeler {
	ret := _m.Called()

	var r0 Modeler
	if rf, ok := ret.Get(0).(func() Modeler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// DeleteAll provides a mock function with given fields:
func (_m *MockedModel) DeleteAll() Modeler {
	ret := _m.Called()

	var r0 Modeler
	if rf, ok := ret.Get(0).(func() Modeler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Exec provides a mock function with given fields: opts
func (_m *MockedModel) Exec(opts ...ExecOption) (int64, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 int64
	if rf, ok := ret.Get(0).(func(...ExecOption) int64); ok {
		r0 = rf(opts...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...ExecOption) error); ok {
		r1 = rf(opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields:
func (_m *MockedModel) Find() Modeler {
	ret := _m.Called()

	var r0 Modeler
	if rf, ok := ret.Get(0).(func() Modeler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Group provides a mock function with given fields: group
func (_m *MockedModel) Group(group string) Modeler {
	ret := _m.Called(group)

	var r0 Modeler
	if rf, ok := ret.Get(0).(func(string) Modeler); ok {
		r0 = rf(group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Having provides a mock function with given fields: having, args
func (_m *MockedModel) Having(having string, args ...interface{}) Modeler {
	var _ca []interface{}
	_ca = append(_ca, having)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 Modeler
	if rf, ok := ret.Get(0).(func(string, ...interface{}) Modeler); ok {
		r0 = rf(having, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Limit provides a mock function with given fields: limit
func (_m *MockedModel) Limit(limit int) Modeler {
	ret := _m.Called(limit)

	var r0 Modeler
	if rf, ok := ret.Get(0).(func(int) Modeler); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Offset provides a mock function with given fields: offset
func (_m *MockedModel) Offset(offset int) Modeler {
	ret := _m.Called(offset)

	var r0 Modeler
	if rf, ok := ret.Get(0).(func(int) Modeler); ok {
		r0 = rf(offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Order provides a mock function with given fields: order
func (_m *MockedModel) Order(order string) Modeler {
	ret := _m.Called(order)

	var r0 Modeler
	if rf, ok := ret.Get(0).(func(string) Modeler); ok {
		r0 = rf(order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Rollback provides a mock function with given fields:
func (_m *MockedModel) Rollback() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SQL provides a mock function with given fields:
func (_m *MockedModel) SQL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Scan provides a mock function with given fields: dest
func (_m *MockedModel) Scan(dest interface{}) Modeler {
	ret := _m.Called(dest)

	var r0 Modeler
	if rf, ok := ret.Get(0).(func(interface{}) Modeler); ok {
		r0 = rf(dest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Select provides a mock function with given fields: columns
func (_m *MockedModel) Select(columns string) Modeler {
	ret := _m.Called(columns)

	var r0 Modeler
	if rf, ok := ret.Get(0).(func(string) Modeler); ok {
		r0 = rf(columns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Tx provides a mock function with given fields:
func (_m *MockedModel) Tx() Txer {
	ret := _m.Called()

	var r0 Txer
	if rf, ok := ret.Get(0).(func() Txer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Txer)
		}
	}

	return r0
}

// Update provides a mock function with given fields:
func (_m *MockedModel) Update() Modeler {
	ret := _m.Called()

	var r0 Modeler
	if rf, ok := ret.Get(0).(func() Modeler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// UpdateAll provides a mock function with given fields: set, args
func (_m *MockedModel) UpdateAll(set string, args ...interface{}) Modeler {
	var _ca []interface{}
	_ca = append(_ca, set)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 Modeler
	if rf, ok := ret.Get(0).(func(string, ...interface{}) Modeler); ok {
		r0 = rf(set, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}

// Where provides a mock function with given fields: condition, args
func (_m *MockedModel) Where(condition string, args ...interface{}) Modeler {
	var _ca []interface{}
	_ca = append(_ca, condition)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 Modeler
	if rf, ok := ret.Get(0).(func(string, ...interface{}) Modeler); ok {
		r0 = rf(condition, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Modeler)
		}
	}

	return r0
}
