name: Examples - WeWatch

on: push

jobs:
  unit-test:
    runs-on: ${{ matrix.platform }}
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
    steps:
      - uses: actions/setup-go@master
        with:
          go-version: 1.13.1
      - uses: actions/setup-node@master
        with:
          go-version: 12.10.0
      - uses: actions/checkout@master
      - run: |
          go version
          node --version
