name: Examples - WeWatch

on: push

jobs:
  examples-wewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@master
        with:
          go-version: 1.13.1
      - uses: actions/setup-node@master
        with:
          node-version: 12.10.0
      - uses: actions/checkout@master
      - working-directory: examples/wewatch/web
        run: npm install
      - working-directory: examples/wewatch
        run: |
          go mod download
          go run . build
          ./wewatch serve &>/dev/null
      - working-directory: examples/wewatch/web
        run: npm run test:e2e -- --url http://0.0.0.0:3000
