name: Examples - WeWatch

on: push

jobs:
  examples-wewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@master
        with:
          go-version: 1.13.1
      - uses: actions/setup-node@master
        with:
          go-version: 12.10.0
      - uses: actions/checkout@master
      - run: |
          go version
          node --version
