name: Examples - WeWatch

on: push

jobs:
  examples-wewatch:
    runs-on: ubuntu-latest
    services:
      pg-master:
        image: bitnami/postgresql:11
        ports:
          - 5432/tcp
        env:
          POSTGRESQL_REPLICATION_MODE: master
          POSTGRESQL_REPLICATION_USER: pg-slave
          POSTGRESQL_REPLICATION_PASSWORD: whatever
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: whatever
          POSTGRESQL_DATABASE: wewatch
      pg-slave:
        image: bitnami/postgresql:11
        ports:
          - 5433/tcp
        env:
          POSTGRESQL_REPLICATION_MODE: slave
          POSTGRESQL_REPLICATION_USER: pg-slave
          POSTGRESQL_REPLICATION_PASSWORD: whatever
          POSTGRESQL_MASTER_HOST: pg-master
          POSTGRESQL_PASSWORD: whatever
          POSTGRESQL_MASTER_PORT_NUMBER: 5432
    steps:
      - uses: actions/setup-go@master
        with:
          go-version: 1.13.1
      - uses: actions/setup-node@master
        with:
          node-version: 12.10.0
      - uses: actions/checkout@master
      - working-directory: examples/wewatch/web
        run: npm install
      - working-directory: examples/wewatch
        run: |
          go mod download
          go run . build
          ./wewatch serve &
        env:
          APPY_MASTER_KEY: ${{ secrets.WEWATCH_APPY_MASTER_KEY_DEVELOPMENT }}
          DB_ADDR_PRIMARY: localhost:${{ job.services.pg-master.ports[5432] }}
      - working-directory: examples/wewatch/web
        run: npm run test:e2e -- --url http://0.0.0.0:3000
