name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      with:
        args: release --skip-validate
      if: success()
