name: Unit Test

on: push

jobs:
  unit-test:
    strategy:
      matrix:
        go: [1.13.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@master
      - run: sudo apt-get install postgresql postgresql-contrib
      - run: make up
      - run: go mod download
      - run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u golang.org/x/lint/golint
          golint -set_exit_status ./... || exit 1
      - run: go vet ./...
      - run: go test -covermode=atomic -coverprofile=coverage.out -tags=test -race -failfast ./...
      - run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
