name: Unit Test

on: push

jobs:
  unit-test:
    strategy:
      matrix:
        go: [1.13.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@master
      - run: sudo apt-get install postgresql-12 postgresql-contrib-12
      - run: make up
      - run: make install
      - run: make codecheck
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
