name: Unit Test

on: push

jobs:
  unit-test:
    strategy:
      matrix:
        go: [1.13.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@master
      - name: Run PostgreSQL 12 installation
        run: |
          sudo apt-get -y install bash-completion wget
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get -y install postgresql-client-12
      - run: make up
      - run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make install
      - run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make codecheck
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
