name: Unit Test

on: push

jobs:
  unit-test:
    strategy:
      matrix:
        go: [1.14.x, 1.15.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@master
      - name: Install PostgreSQL 12
        run: |
          sudo apt-get -y install bash-completion wget
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get -y install mysql-client postgresql-client-12
      - name: Install Project Dependencies
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make install
      - name: Setup Local Data Store
        run: make up
      - name: Run Unit Test
        run: make test
      - name: Send Code Coverage To CodeCov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
